

INSERT INTO FLIGHT(ID,AIRLINE_NAME,FLIGHT_NUMBER,DEPARTURE_DATE,DEPARTURE_TIME) VALUES (1, 'Air Canada', '8099', CURRENT_DATE, CAST ('07:30' AS TIME));
INSERT INTO FLIGHT(ID,AIRLINE_NAME,FLIGHT_NUMBER,DEPARTURE_DATE,DEPARTURE_TIME) VALUES (2, 'United Airline', '6115', CURRENT_DATE, CAST ('10:30' AS TIME));
INSERT INTO FLIGHT(ID,AIRLINE_NAME,FLIGHT_NUMBER,DEPARTURE_DATE,DEPARTURE_TIME) VALUES (3, 'WestJet', '6456', CURRENT_DATE, CAST ('12:30' AS TIME));
INSERT INTO FLIGHT(ID,AIRLINE_NAME,FLIGHT_NUMBER,DEPARTURE_DATE,DEPARTURE_TIME) VALUES (4, 'Delta', '8099', CURRENT_DATE, CAST ('15:00' AS TIME));